version: '3.8'

services:
  # Serviço para o Postgre
  postgres:
    image: postgres:15
    container_name: postgres_database
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=caio_teste
      - POSTGRES_USER=caio
      - POSTGRES_PASSWORD=by302OQCcDYKSlF42DaxHzj9n9W7jPoO
    volumes:
      - ./src/main/resources/scripts:/docker-entrypoint-initdb.d
# Serviço para a sua aplicação Java
  java_app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
